### ISSUE TITLE
[urwid client]  Options menu | Misaligned choices

### ISSUE THREAD

**Issue by aelaraji** [bbj-dev/bbj#24]
## The issue:
I don't know if it's just me, but if I go to Options with the `o` key, scroll down like usual. The `Text Editor:` section's choices are misaligned and appear below the `Date Format` one. 

![Screenshot of urwid Options menu](https://github.com/user-attachments/assets/4b4c401e-5d70-43d5-9631-1bf0f2293f8a)

## How I'm actually running the client:
- I've just cloned the repo and changed directory into it.
- (not sure if it's relevant) my bbj password is stored using `pass` so it's fed to `urwid` through the environment variable like this: 

```bash
BBJ_PASSWORD="$(pass bbj)" python3 path/to/urwid/main.py --host bbj.example.ltd --user username
```

## System info:
OS: OpenSUSE Tumbleweed 
```bash
» uname --operating-system  --kernel-release --hardware-platform
6.11.8-1-default x86_64 GNU/Linux
```
```bash
» python3 --version
Python 3.11.10
```

**Comment by aelaraji** [comment]
Fixed! 🙏

**Comment by desvox** [comment]
> Fixed! 🙏

good! I forget to look at the issues here, sorry I didn't finish this sooner
